import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import NavigationBar from "@/components/navigation-bar";
import { LINKS, LOGO } from "@/constants";

export const metadata: Metadata = {
  title: "SDUSD JROTC",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <header>
          <NavigationBar links={LINKS} logo={LOGO} />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
