import { Metadata } from "next";

export const metadata: Metadata = {
  title: "SDUSD JROTC | Brigade Awards",
  description: "Generated by create next app",
};

export default function BrigadeAwardsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main>{children}</main>;
}
